use argon2::{Argon2, PasswordHasher, password_hash::SaltString};
use chrono::{DateTime, Utc};
use ib_utils::{Token, define_token_prefix};

use crate::types::Capabilities;

define_token_prefix!(UserTokenPrefix, "U_");

pub type UserId = u64;
pub type UserToken = Token<UserTokenPrefix, UserId, { i64::MAX as u128 }>;

#[derive(Debug, Clone)]
pub struct User {
    pub id: UserId,
    pub token: UserToken,
    pub username: String,
    pub full_name: String,
    pub password_hash: String,
    pub email_address: String,
    pub capabilities: Capabilities,
    pub change_password_on_login: bool,
    pub version: u64,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Input for creating a new user. System-assigned fields (id, token, version,
/// timestamps) are generated by the repository on insert.
#[derive(Debug, Clone)]
pub struct NewUser {
    pub username: String,
    pub full_name: String,
    pub password_hash: String,
    pub email_address: String,
    pub capabilities: Capabilities,
    pub change_password_on_login: bool,
}

impl NewUser {
    pub fn new(
        username: impl Into<String>,
        password: &str,
        email_address: impl Into<String>,
        full_name: impl Into<String>,
        capabilities: Capabilities,
        change_password_on_login: bool,
    ) -> Result<Self, crate::Error> {
        let full_name = full_name.into();
        if full_name.trim().is_empty() {
            return Err(crate::Error::Validation("full_name must not be empty".into()));
        }

        let password_hash = Self::hash_password(password)?;

        Ok(Self {
            username: username.into(),
            full_name,
            password_hash,
            email_address: email_address.into(),
            capabilities,
            change_password_on_login,
        })
    }

    fn hash_password(password: &str) -> Result<String, crate::Error> {
        let salt = SaltString::generate(&mut argon2::password_hash::rand_core::OsRng);
        Argon2::default()
            .hash_password(password.as_bytes(), &salt)
            .map(|h| h.to_string())
            .map_err(|e| crate::Error::CryptoError(e.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_token_displays_with_prefix_and_roundtrips() {
        let token = UserToken::new(42);
        let s = token.to_string();
        assert!(s.starts_with("U_"), "expected U_ prefix, got {s}");
        let parsed = UserToken::parse(&s).expect("should parse back");
        assert_eq!(parsed.id(), 42);
    }
}
