use argon2::{Argon2, PasswordHasher, password_hash::SaltString};
use chrono::{DateTime, Utc};
use ib_utils::{Token, define_token_prefix};
use serde::{Deserialize, Serialize};

define_token_prefix!(UserTokenPrefix, "U_");

pub type UserId = u64;
pub type UserToken = Token<UserTokenPrefix, UserId, { i64::MAX as u128 }>;

/// A capability that can be granted to a user.
///
/// Global capabilities (SuperAdmin, Admin) are stored on `User.capabilities`.
/// Per-project capabilities (ViewIssues, etc.) are stored on
/// `ProjectMember.capabilities`. Both use the same enum for a unified
/// permission model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum Capability {
    // Global
    SuperAdmin,
    Admin,
    // Per-project
    ViewIssues,
    CreateIssues,
    UpdateIssues,
    TransitionStatus,
    ManageLabels,
    ManageMembers,
}

/// A set of capabilities stored as a JSON array.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct Capabilities(pub Vec<Capability>);

impl Capabilities {
    pub fn has(&self, cap: Capability) -> bool {
        self.0.contains(&cap)
    }

    pub fn is_super_admin(&self) -> bool {
        self.has(Capability::SuperAdmin)
    }
}

#[derive(Debug, Clone)]
pub struct User {
    pub id: UserId,
    pub token: UserToken,
    pub username: String,
    pub full_name: String,
    pub password_hash: String,
    pub email_address: String,
    pub api_key_hash: Option<String>,
    pub api_key_prefix: Option<String>,
    pub api_key_created_at: Option<DateTime<Utc>>,
    pub api_key_last_used_at: Option<DateTime<Utc>>,
    pub capabilities: Capabilities,
    pub change_password_on_login: bool,
    pub version: u64,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Input for creating a new user. System-assigned fields (id, token, version,
/// timestamps) are generated by the repository on insert.
#[derive(Debug, Clone)]
pub struct NewUser {
    pub username: String,
    pub full_name: String,
    pub password_hash: String,
    pub email_address: String,
    pub capabilities: Capabilities,
    pub change_password_on_login: bool,
}

impl NewUser {
    pub fn new(
        username: impl Into<String>,
        password: &str,
        email_address: impl Into<String>,
        full_name: impl Into<String>,
        capabilities: Capabilities,
        change_password_on_login: bool,
    ) -> Result<Self, crate::Error> {
        let full_name = full_name.into();
        if full_name.trim().is_empty() {
            return Err(crate::Error::Validation("full_name must not be empty".into()));
        }

        let password_hash = Self::hash_password(password)?;

        Ok(Self {
            username: username.into(),
            full_name,
            password_hash,
            email_address: email_address.into(),
            capabilities,
            change_password_on_login,
        })
    }

    fn hash_password(password: &str) -> Result<String, crate::Error> {
        let salt = SaltString::generate(&mut argon2::password_hash::rand_core::OsRng);
        Argon2::default()
            .hash_password(password.as_bytes(), &salt)
            .map(|h| h.to_string())
            .map_err(|e| crate::Error::CryptoError(e.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_token_displays_with_prefix_and_roundtrips() {
        let token = UserToken::new(42);
        let s = token.to_string();
        assert!(s.starts_with("U_"), "expected U_ prefix, got {s}");
        let parsed = UserToken::parse(&s).expect("should parse back");
        assert_eq!(parsed.id(), 42);
    }

    #[test]
    fn capabilities_roundtrip_serde() {
        let caps = Capabilities(vec![Capability::SuperAdmin, Capability::Admin]);
        let json = serde_json::to_string(&caps).unwrap();
        assert_eq!(json, r#"["SuperAdmin","Admin"]"#);
        let caps2: Capabilities = serde_json::from_str(&json).unwrap();
        assert_eq!(caps2.0, vec![Capability::SuperAdmin, Capability::Admin]);
    }

    #[test]
    fn capabilities_has_works() {
        let caps = Capabilities(vec![Capability::SuperAdmin]);
        assert!(caps.has(Capability::SuperAdmin));
        assert!(!caps.has(Capability::Admin));
    }
}
