[package]
name = "ib-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
tokio-graceful-shutdown.workspace = true
anyhow.workspace = true
tracing.workspace = true
dioxus.workspace = true

[dev-dependencies]
tower = { workspace = true }
