[package]
name = "integration-tests"
description = "IssueBoss integration tests"
publish = false
autotests = false
autobins = false

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[test]]
name = "integration"
path = "src/main.rs"

[features]
default = ["postgres"]
postgres = ["dep:testcontainers", "dep:testcontainers-modules"]
sqlite = []

[dependencies]
ib-core.workspace = true
ib-database.workspace = true

async-trait.workspace = true
chrono.workspace = true
sea-orm.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dependencies.testcontainers]
workspace = true
optional = true

[dependencies.testcontainers-modules]
workspace = true
optional = true

[lints]
workspace = true
