[package]
name = "ib-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ib-core.workspace = true

anyhow.workspace = true
axum.workspace = true
tokio-graceful-shutdown.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tower = { workspace = true }

[lints]
workspace = true
