[package]
name = "issueboss"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "issueboss"
path = "src/main.rs"

[dependencies]
ib-core.workspace = true
ib-database.workspace = true
ib-api.workspace = true
ib-frontend.workspace = true
tokio.workspace = true
tokio-graceful-shutdown.workspace = true
config.workspace = true
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

