[package]
name = "ib-api"
description = "IssueBoss API support"
autotests = false

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

build = "build.rs"

[dependencies]
ib-core.workspace = true

axum.workspace = true
prost.workspace = true
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio-graceful-shutdown.workspace = true
tokio.workspace = true
tonic-prost.workspace = true
tonic-reflection.workspace = true
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
chrono.workspace = true
ib-core = { workspace = true, features = ["test-support"] }
mockall.workspace = true
tokio.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true

[lints]
workspace = true
